name: Summarize SVS SBOMs
description: 👋 Greet someone and record the time

inputs:
    filename:
        description: "The filename containing the individual sboms of the SVS-repos"

    repos:
        description: "Semicolon-separated list of repositories and their versions {repo}@{version}"

outputs:
    json:
        description: "The summarizing JSON of all dependencies grouped by license."

runs:
    using: node20
    main: ./dist/index.js
